name: Regenerate README.md

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 17 * * *'

jobs:
  generate_readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Generate README.md
        run: npm run render
        env:
          RAPID_API_KEY: ${{ secrets.RAPID_API_KEY }}
      - name: Push new README.md
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'